global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 30s

    relabel_configs:
      # Only scrape containers with prometheus.scrape=true
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep

      # Set target address = container_ip:prometheus.scrape.port
      - source_labels: [__meta_docker_container_network_ip, __meta_docker_container_label_prometheus_scrape_port]
        regex: "(.+);(.+)"
        replacement: "$1:$2"
        target_label: __address__

      # If prometheus.scrape.path is set, use it; otherwise default to /metrics
      - source_labels: [__meta_docker_container_label_prometheus_scrape_path]
        regex: "(.+)"
        target_label: __metrics_path__
        action: replace
      - source_labels: [__meta_docker_container_label_prometheus_scrape_path]
        regex: ""
        replacement: "/metrics"
        target_label: __metrics_path__

      # Add container/job labels
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
