networks:
  homelab:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:2.26.0
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - homelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.${LOCAL_DOMAIN}`) || Host(`portainer.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      
      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.${LOCAL_DOMAIN}`) || Host(`edge.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"


volumes:
  portainer_data: