networks:
    homelab:
        external: true

services:
    it-tools:
        image: 'corentinth/it-tools:latest'
        restart: unless-stopped
        container_name: it-tools
        networks:
        - homelab
        labels:
            traefik.enable: "true"
            traefik.http.routers.it-tools.rule: "Host(`ittools.${LOCAL_DOMAIN}`) || Host(`ittools.${PUBLIC_DOMAIN}`)"
            traefik.http.routers.it-tools.entrypoints: "web"
            traefik.http.services.it-tools.loadbalancer.server.port: "80"