---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Services:
    - Portainer:
        icon: portainer.png
        href: http://portainer.dkc26.live # change to your portainer URL
        widget:
          type: portainer
          url: http://portainer:9000
          env: 1
          key: ptr_/Fnt5kKiHGOq/Liee2Fp9gFlAmcDBbIe+8aZHCaTzTI=

- Tunnel Status:
    - Cloudflared:
        icon: cloudflare.png
        ping: http://dashboard.dkc26.live # change to your portainer URL
        widget:
          type: cloudflared
          accountid: 185be7abe90bab0286b6cd9b1df6d4ae
          tunnelid: 47c7d02a-3619-465c-8cf1-f03b418b8898
          key: Kh26nDZyF94DXY2DJ-i1IEQchQ7lQCt422tf6bD8

- Local DNS:
    - pihole:
        icon: pi-hole.png
        href: http://pihole.dkc26.live/admin # change to your portainer URL
        widget:
          type: pihole
          url: http://pihole
          key: 01b613da484bee91c3f3806b52a6f40fd61ade874b5ffc0f62a2091cce38158b

- Reverse Proxy:
    - traefik:
        icon: traefik.png
        href: http://traefik.dkc26.live/ # change to your portainer URL
        widget:
            type: traefik
            url: http://traefik:8080
            username: admin
            password: pass
- Quick Links:
    - Jellifin:
        icon: si-jellyfin
        href: http://jellyfin.dkc26.live/ # change to your portainer URL
        container: jellyfin
    #     widget:
    #         type: jellyfin
    #         url: http://jellyfin
    #         key: apikeyapikeyapikeyapikeyapikey
    #         enableBlocks: true
    #         enableNowPlaying: true
    #         enableUser: true
    #         showEpisodeNumber: true
    #         expandOneStreamToTwoRows: false
    - Kestra:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/kestra.png
        href: http://kestra.dkc26.live/ # change to your portainer URL
        container: kestra
