---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: My Dashboard

theme: dark 
color: slate 

background: 
  image: https://images.unsplash.com/photo-1735809489088-ead6b62e5ac5?q=80&w=1470&auto=format&fit=crop
  blur: sm 


# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey
